import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Script from 'next/script';
import Navbar from '@/components/Navbar';

const Poppins = localFont({
  src: [
    {
      path: '/fonts/Poppins-Black.ttf',
      weight: '900',
      style: 'black',
    },
    {
      path: '/fonts/Poppins-ExtraBold.ttf',
      weight: '800',
      style: 'extrabold',
    },
    {
      path: '/fonts/Poppins-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '/fonts/Poppins-SemiBold.ttf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: '/fonts/Poppins-Light.ttf',
      weight: '500',
      style: 'light',
    },
    {
      path: '/fonts/Poppins-Medium.ttf',
      weight: '400',
      style: 'medium',
    },
    {
      path: '/fonts/Poppins-Regular.ttf',
      weight: '300',
      style: 'regular',
    },
    {
      path: '/fonts/Poppins-Thin.ttf',
      weight: '200',
      style: 'thin',
    },
  ],
  variable: '--poppins-font',
});

export const metadata: Metadata = {
  title: 'HUMMINGBUD',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Poppins.variable}>
        <Navbar />
        {children}
        <Script
          src="https://kit.fontawesome.com/f8552ba515.js"
          crossOrigin="anonymous"
        ></Script>
      </body>
    </html>
  );
}
